In [8]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv(
    "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day34-handling-date-and-time/orders.csv"
)
time=pd.read_csv(
    "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day34-handling-date-and-time/messages.csv"
)

In [10]:
data.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [11]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [13]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with Dates

In [14]:
date.drop(columns=['product_id','city_id','orders'],axis=1,inplace=True)

In [15]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])
time['date'] = pd.to_datetime(time['date'])

In [16]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

## 1 Extract year

In [17]:
# date of year
date['date_year']=date['date'].dt.year
date.head(2)

        date  date_year
0 2019-12-10       2019
1 2018-08-15       2018

In [18]:
# day of month number
date['date_month_no.']=date['date'].dt.month
date.head(2)

        date  date_year  date_month_no.
0 2019-12-10       2019              12
1 2018-08-15       2018               8

### If you need month

In [19]:
# day of month with name
date['date_month_name']=date['date'].dt.month_name()
date.head(2)

        date  date_year  date_month_no. date_month_name
0 2019-12-10       2019              12        December
1 2018-08-15       2018               8          August

## Extract Days

In [20]:
# day of week
date['date_day']=date['date'].dt.day
date.head(2)

        date  date_year  date_month_no. date_month_name  date_day
0 2019-12-10       2019              12        December        10
1 2018-08-15       2018               8          August        15

In [21]:
# day with name
date['date_day_name']=date['date'].dt.day_name()
date.head(2)

,date,date_year,date_month_no.,date_month_name,date_day,date_day_name
0,2019-12-10,2019,12,December,10,Tuesday
1,2018-08-15,2018,8,August,15,Wednesday

In [22]:
# day of week
date['date_dow']=date['date'].dt.dayofweek
date.head(2)

,date,date_year,date_month_no.,date_month_name,date_day,date_day_name,date_dow
0,2019-12-10,2019,12,December,10,Tuesday,1
1,2018-08-15,2018,8,August,15,Wednesday,2

In [23]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()
date.head(2)

,date,date_year,date_month_no.,date_month_name,date_day,date_day_name,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,Tuesday,1,Tuesday
1,2018-08-15,2018,8,August,15,Wednesday,2,Wednesday

## Is weekend ?

In [24]:
date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.head(2)

,date,date_year,date_month_no.,date_month_name,date_day,date_day_name,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,Tuesday,1,Tuesday,0
1,2018-08-15,2018,8,August,15,Wednesday,2,Wednesday,0

## Extract week of the year

In [25]:
# date['date_week']=date['date'].dt.week  # This is old version removed from the pandas new version
date['date_week'] = date['date'].dt.isocalendar().week
date.head(2)

,date,date_year,date_month_no.,date_month_name,date_day,date_day_name,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,Tuesday,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,Wednesday,2,Wednesday,0,33

## Extract Quater

In [26]:

date['quarter'] = date['date'].dt.quarter
date.head(2)

,date,date_year,date_month_no.,date_month_name,date_day,date_day_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,Tuesday,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,Wednesday,2,Wednesday,0,33,3

## Extract Semester

In [27]:
print(date.columns.tolist())

['date', 'date_year', 'date_month_no.', 'date_month_name', 'date_day', 'date_day_name', 'date_dow', 'date_dow_name', 'date_is_weekend', 'date_week', 'quarter']

In [28]:
date['semester'] = np.where(
    date['quarter'].isin([1, 2]),
    1,
    2
)
date.head(5)

,date,date_year,date_month_no.,date_month_name,date_day,date_day_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,Tuesday,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,Wednesday,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,Tuesday,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,Saturday,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,Sunday,6,Sunday,1,1,1,1

## Extract Time elapsed between dates

In [29]:
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 9, 16, 22, 2, 41, 445210)

In [30]:
# Total year
(today - date['date']).dt.days / 365

0      6.772603
1      8.093151
2      7.904110
3      7.087671
4      7.698630
         ...
995    7.945205
996    7.783562
997    7.367123
998    7.545205
999    6.926027
Name: date, Length: 1000, dtype: float64

In [31]:
# Total month
(today.year - date['date'].dt.year) * 12 + (today.month - date['date'].dt.month)

0      81
1      97
2      95
3      85
4      92
       ..
995    95
996    93
997    88
998    90
999    83
Name: date, Length: 1000, dtype: int32

In [32]:
# Total days
today - date['date']

0     2472 days 22:02:41.445210
1     2954 days 22:02:41.445210
2     2885 days 22:02:41.445210
3     2587 days 22:02:41.445210
4     2810 days 22:02:41.445210
                 ...
995   2900 days 22:02:41.445210
996   2841 days 22:02:41.445210
997   2689 days 22:02:41.445210
998   2754 days 22:02:41.445210
999   2528 days 22:02:41.445210
Name: date, Length: 1000, dtype: timedelta64[ns]

# Time dataset

In [33]:
today - time['date']

0     4658 days 21:12:41.445210
1     4522 days 22:22:41.445210
2     5008 days 21:41:41.445210
3     4310 days 21:31:41.445210
4     4707 days 22:51:41.445210
                 ...
995   5297 days 21:12:41.445210
996   4618 days 22:48:41.445210
997   5083 days 22:25:41.445210
998   5199 days 22:28:41.445210
999   4471 days 22:37:41.445210
Name: date, Length: 1000, dtype: timedelta64[ns]

In [34]:
(today - time['date']).dt.days / 365

0      12.761644
1      12.389041
2      13.720548
3      11.808219
4      12.895890
         ...
995    14.512329
996    12.652055
997    13.926027
998    14.243836
999    12.249315
Name: date, Length: 1000, dtype: float64

In [35]:
(today - time['date']).dt.days

0      4658
1      4522
2      5008
3      4310
4      4707
       ...
995    5297
996    4618
997    5083
998    5199
999    4471
Name: date, Length: 1000, dtype: int64

In [36]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      111813.211513
1      108550.378179
2      120213.694846
3      103461.528179
4      112990.861513
           ...
995    127149.211513
996    110854.811513
997    122014.428179
998    124798.478179
999    107326.628179
Name: date, Length: 1000, dtype: float64