In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [56]:
df=pd.read_csv("Messy_Employee_dataset.csv")

In [57]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [58]:
df.shape

(1020, 12)

In [59]:
df.drop(['First_Name','Last_Name','Salary','Phone','Email','Status','Remote_Work'],axis=1,inplace=True)

In [60]:
df.columns.tolist()

['Employee_ID', 'Age', 'Department_Region', 'Join_Date', 'Performance_Score']

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   Age                809 non-null    float64
 2   Department_Region  1020 non-null   object
 3   Join_Date          1020 non-null   object
 4   Performance_Score  1020 non-null   object
dtypes: float64(1), object(4)
memory usage: 40.0+ KB

In [62]:
df.shape

(1020, 5)

In [63]:
df.head(3)

  Employee_ID   Age  Department_Region  Join_Date Performance_Score
0     EMP1000  25.0  DevOps-California   4/2/2021           Average
1     EMP1001   NaN      Finance-Texas  7/10/2020         Excellent
2     EMP1002   NaN       Admin-Nevada  12/7/2023              Good

In [64]:
df['categ_id']=df['Employee_ID'].str.extract('([A-Za-z]+)')

In [65]:
df.head(2)

  Employee_ID   Age  Department_Region  Join_Date Performance_Score categ_id
0     EMP1000  25.0  DevOps-California   4/2/2021           Average      EMP
1     EMP1001   NaN      Finance-Texas  7/10/2020         Excellent      EMP

In [66]:
df['num_id']=df['Employee_ID'].str.extract('(\d+)')

In [67]:
df.head(2)

,Employee_ID,Age,Department_Region,Join_Date,Performance_Score,categ_id,num_id
0,EMP1000,25.0,DevOps-California,4/2/2021,Average,EMP,1000
1,EMP1001,NaN,Finance-Texas,7/10/2020,Excellent,EMP,1001

In [68]:
df['Job_Title']=df['Department_Region'].apply(lambda s : s.split('-')[0])

In [69]:
df.head(2)

,Employee_ID,Age,Department_Region,Join_Date,Performance_Score,categ_id,num_id,Job_Title
0,EMP1000,25.0,DevOps-California,4/2/2021,Average,EMP,1000,DevOps
1,EMP1001,NaN,Finance-Texas,7/10/2020,Excellent,EMP,1001,Finance

In [70]:
df.isnull().sum()

Employee_ID            0
Age                  211
Department_Region      0
Join_Date              0
Performance_Score      0
categ_id               0
num_id                 0
Job_Title              0
dtype: int64

In [71]:
df['Join_Date']=pd.to_datetime(df['Join_Date'])

In [72]:
df['Join_Date'].dtype

dtype('<M8[ns]')

In [73]:
import datetime
today=datetime.datetime.today()

In [74]:
today

datetime.datetime(2026, 9, 17, 11, 6, 19, 43540)

In [75]:
(today-df['Join_Date']).dt.days/365

0       5.463014
1       6.191781
2       2.780822
3       4.808219
4       4.701370
          ...
1015    3.082192
1016    4.863014
1017    2.956164
1018    1.753425
1019    5.569863
Name: Join_Date, Length: 1020, dtype: float64

In [76]:
df['YearOfJoin']=df['Join_Date'].dt.year

In [77]:
df['MonthOfJoin']=df['Join_Date'].dt.month_name()

In [78]:
df

,Employee_ID,Age,Department_Region,Join_Date,Performance_Score,categ_id,num_id,Job_Title,YearOfJoin,MonthOfJoin
0,EMP1000,25.0,DevOps-California,2021-04-02,Average,EMP,1000,DevOps,2021,April
1,EMP1001,NaN,Finance-Texas,2020-07-10,Excellent,EMP,1001,Finance,2020,July
2,EMP1002,NaN,Admin-Nevada,2023-12-07,Good,EMP,1002,Admin,2023,December
3,EMP1003,25.0,Admin-Nevada,2021-11-27,Good,EMP,1003,Admin,2021,November
4,EMP1004,25.0,Cloud Tech-Florida,2022-01-05,Poor,EMP,1004,Cloud Tech,2022,January
...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,30.0,HR-California,2023-08-19,Good,EMP,2015,HR,2023,August
1016,EMP2016,30.0,Cloud Tech-Texas,2021-11-07,Good,EMP,2016,Cloud Tech,2021,November
1017,EMP2017,40.0,Finance-New York,2023-10-04,Average,EMP,2017,Finance,2023,October
1018,EMP2018,30.0,HR-Florida,2024-12-16,Good,EMP,2018,HR,2024,December
1019,EMP2019,30.0,DevOps-Illinois,2021-02-22,Average,EMP,2019,DevOps,2021,February

In [79]:
df.isnull().mean()*100

Employee_ID           0.000000
Age                  20.686275
Department_Region     0.000000
Join_Date             0.000000
Performance_Score     0.000000
categ_id              0.000000
num_id                0.000000
Job_Title             0.000000
YearOfJoin            0.000000
MonthOfJoin           0.000000
dtype: float64